;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname area-of-disk) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(define (area-of-disk x)
  (* 3.14 (* x x)))
(define (area-of-ring outer inner)
  (- (area-of-disk outer) (area-of-disk inner)))
(define (test-sqrt x)
  (sqrt x))
(define (test-expt a b)
  (expt a b))
(define (test-remainder a b)
  (remainder a b))
(define (test-ch a b)
  (/ a b))
(define (test-log a)
  (log a))
(define (test-sin x)
  (sin x))
(define (convert x y z)
  (+ (* 100 z) (+ (* 10 y) x)))
(define (f x)
   x )